const test=require('node:test');
const assert=require('node:assert/strict');
const {createContext,plain}=require('./helpers/synth-context');
const names=['Breathr','Choirr','Pluckr'];
function setup(){const api=createContext(names);api.run('Math.random=SoundDSP.rng(0.3917)');return api;}
function rms(a){return Math.sqrt(a.reduce((s,v)=>s+v*v,0)/a.length);}
function safe(a){assert.ok(a.length>=0.15*44100&&a.length<=5*44100);assert.ok(a.every(v=>Number.isFinite(v)&&Math.abs(v)<1));assert.equal(Math.abs(a[0]),0);assert.equal(Math.abs(a.at(-1)),0);assert.ok(rms(a)>0.0001);}
for(const name of names){
 test(name+' recipes are fresh, audible, repeatable snapshots',()=>{const {run}=setup();run(`var s=new ${name}()`);const recipes=plain(run('s.recipes'));assert.equal(recipes.length,name==='Breathr'?9:8);for(const r of recipes){const a=plain(run(`s.generate_recipe('${r.id}');s.params`));const b=plain(run(`s.generate_recipe('${r.id}');s.params`));assert.ok(Object.keys(a).filter(k=>k!=='seed'&&a[k]!==b[k]).length>=3,r.id);assert.notEqual(a.seed,b.seed);const pcm=run('s.generate_sound();s.sound.getBuffer().slice()');safe(pcm);assert.deepEqual(pcm,run('s.generate_sound();s.sound.getBuffer()'));assert.notDeepEqual(pcm,run('s.set_param("seed",0.73);s.generate_sound();s.sound.getBuffer()'));}});
 test(name+' respects locks, complete duration, extremes and mute',()=>{const {run}=setup();run(`var s=new ${name}()`);assert.ok(run(`s.generate_recipe(s.recipes[0].id);Object.keys(s.params).forEach(k=>s.set_locked_param(k,true));var before=JSON.stringify(s.params);s.recipes.forEach(r=>s.generate_recipe(r.id));s.randomize_params();s.mutate_params();before===JSON.stringify(s.params)`));run(`s=new ${name}()`);for(const end of ['min','max']){const pcm=run(`s.param_info.forEach(info=>{var p=s.get_param_normalized(info);if(p.type!=='BUTTONSELECT')s.set_param(p.name,p.${end}_value);});s.set_param('masterVolume',1);s.set_param('duration',0.25);${name}_DSP.render(s.params)`);safe(pcm);}assert.equal(run(`s.set_param('duration',5);${name}_DSP.render(s.params).length`),220500);assert.ok(run(`s.set_param('masterVolume',0);${name}_DSP.render(s.params).every(v=>v===0)`));});
}
test('breathing has a controllable silent held-air interval',()=>{const {run}=setup();const [a,b]=run(`var p={duration:2,cycles:1,hold:0,inhale:0.4,space:0,seed:0.5};var a=Breathr_DSP.render(p);p.hold=0.65;[a,Breathr_DSP.render(p)]`);assert.ok(rms(b.slice(27000,53000))<rms(a.slice(27000,53000))*0.15);});
test('choir harmony and vowel independently change the sustained ensemble',()=>{const {run}=setup();const [a,b,c]=run(`var p={duration:0.7,voices:6,harmony:0,vowel:0,seed:0.5};var a=Choirr_DSP.render(p);p.harmony=1;var b=Choirr_DSP.render(p);p.vowel=1;[a,b,Choirr_DSP.render(p)]`);safe(a);safe(b);safe(c);assert.notDeepEqual(a,b);assert.notDeepEqual(b,c);});
test('plucked strings ring at a pitched period and damping shortens their decay',()=>{const {run}=setup();const [a,b]=run(`var p={duration:2,pitch:0.5,strings:1,damping:0,brightness:0.8,coupling:0,strum:0,seed:0.5};var a=Pluckr_DSP.render(p);p.damping=1;[a,Pluckr_DSP.render(p)]`);const lag=Math.round(44100/(55*2**(0.5*4)));let cross=0,power=0;for(let i=9000;i<13000;i++){cross+=a[i]*a[i+lag];power+=a[i]*a[i];}assert.ok(cross/power>0.6);assert.ok(rms(a.slice(40000,60000))>rms(b.slice(40000,60000))*3);});
test('count setters round validated numeric values and respect locked values',()=>{const {run}=setup();for(const [name,key] of [['Breathr','cycles'],['Choirr','voices'],['Pluckr','strings']]){assert.ok(run(`var s=new ${name}();s.set_param('${key}',3.7);Number.isInteger(s.params.${key})`));assert.ok(run(`s.set_locked_param('${key}',true);var saved=s.params.${key};s.set_param('${key}',8,true);saved===s.params.${key}`));}});

test('extreme feedback loops remain finite before output conditioning',()=>{const {run}=setup();assert.ok(run(`var original=SoundDSP.finish;var valid=true;SoundDSP.finish=(buffer,volume)=>{valid=valid&&buffer.every(v=>Number.isFinite(v)&&Math.abs(v)<100);return original.call(SoundDSP,buffer,volume);};var s=new Pluckr();s.param_info.forEach(info=>{var p=s.get_param_normalized(info);s.set_param(p.name,p.max_value);});s.set_param('duration',1);Pluckr_DSP.render(s.params);valid;`));});
