"""Regenerate browser speech data from pinned upstream files (standard library only).

Usage: python3 tools/data/build_chattr.py /path/to/downloads
Download filenames/URLs are listed in SOURCES. No network occurs in this script.
"""
import hashlib
import json
from pathlib import Path
import re
import sys

KLATT = '43189e6f9f311e9514cc0809b080d0ccb9eb746d'
CMU = '74790861f652b15e4ac49015a90074ad62a27690'
SOURCES = {
    'chattr-dsp.js': f'https://raw.githubusercontent.com/tgies/klattsch/{KLATT}/src/engine/dsp.js',
    'chattr-synth-core.js': f'https://raw.githubusercontent.com/tgies/klattsch/{KLATT}/src/engine/synth-core.js',
    'chattr-phoneme-bank.json': f'https://raw.githubusercontent.com/tgies/klattsch/{KLATT}/src/engine/banks/klatt1980-en.json',
    'chattr-klattsch.LICENSE': f'https://raw.githubusercontent.com/tgies/klattsch/{KLATT}/LICENSE',
    'chattr-cmudict.dict': f'https://raw.githubusercontent.com/cmusphinx/cmudict/{CMU}/cmudict.dict',
    'chattr-cmudict.LICENSE': f'https://raw.githubusercontent.com/cmusphinx/cmudict/{CMU}/LICENSE',
}
root = Path(__file__).resolve().parents[2]
source = Path(sys.argv[1])
files = {name: (source / name).read_text() for name in SOURCES}
notice = '# Chattr third-party sources\n\nGenerated by `tools/data/build_chattr.py`. The engine has a module wrapper and an optional oscillator source callback; phoneme scheduling and voice controls belong to Chattr. The dictionary keeps the first pronunciation of each English word, encoded as one letter per phoneme plus stress digits. No runtime download or speech service is used.\n\n'
for name, url in SOURCES.items():
    notice += f'- [{name}]({url}), SHA256 `{hashlib.sha256((source/name).read_bytes()).hexdigest()}`\n'
notice += '\n## klattsch (engine and English formants)\n\n' + files['chattr-klattsch.LICENSE']
notice += '\n## CMU Pronouncing Dictionary\n\n' + files['chattr-cmudict.LICENSE']
(root/'THIRD_PARTY_CHATTR.md').write_text(notice)

dsp = files['chattr-dsp.js'].replace('export ', '')
core = re.sub(r'^import .*?;\n', '', files['chattr-synth-core.js'], flags=re.M).replace('export ', '')
# Keep the original vocal source as the default, with an optional Bfxr oscillator.
core = core.replace('constructor({ sampleRate, initialTarget, schedule } = {})',
    'constructor({ sampleRate, initialTarget, schedule, source } = {})')
core = core.replace('    this.sr = sampleRate;', '    this.sr = sampleRate;\n    this.source = source;')
core = core.replace('const pulseVal = glottalPulse(this.glottalPhase, cur.effort);',
    'const pulseVal = this.source ? this.source(this.glottalPhase, effF0 / this.sr) * 0.55 : glottalPulse(this.glottalPhase, cur.effort);')
bank = json.loads(files['chattr-phoneme-bank.json'])['phonemes']
header = '// Generated by tools/data/build_chattr.py; see THIRD_PARTY_CHATTR.md.\n'
# Licenses are data on the public object, so the existing single-file minifier retains them.
(root/'js/audio/ChattrFormants.js').write_text(header + 'const ChattrFormants = (() => {\n' + dsp + core +
    '\nreturn {FormantSynth, bank:' + json.dumps(bank, separators=(',', ':')) +
    ', license:' + json.dumps(files['chattr-klattsch.LICENSE']) + '};\n})();\n')

phones = sorted(k for k in bank if k != '_')
alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
encoding = {p: alphabet[i] for i, p in enumerate(phones)}
rows = {}
for line in files['chattr-cmudict.dict'].splitlines():
    fields = line.split('#', 1)[0].split()
    if len(fields) < 2 or not re.fullmatch(r"[a-z]+(?:'[a-z]+)*", fields[0]):
        continue
    word, *pronunciation = fields
    if word in rows:
        continue
    rows[word] = ''.join(encoding[re.sub('[012]$', '', p)] + (p[-1] if p[-1].isdigit() else '') for p in pronunciation)
# Front-code sorted words to reduce duplication without a decompressor dependency.
previous = ''
data = []
for word, encoded in sorted(rows.items()):
    common = 0
    while common < min(len(previous), len(word)) and previous[common] == word[common]:
        common += 1
    data.append(str(common) + ' ' + word[common:] + ' ' + encoded)
    previous = word
body = '''
    let dictionary;
    return {
        license: LICENSE,
        lookup(word) {
            if (!dictionary) {
                dictionary = Object.create(null);
                let previous = '';
                for (const row of DATA.split('\\n')) {
                    const [prefix, suffix, encoded] = row.split(' ');
                    const current = previous.slice(0, Number(prefix)) + suffix;
                    dictionary[current] = encoded;
                    previous = current;
                }
            }
            const encoded = dictionary[word];
            if (!encoded) return null;
            const result = [];
            for (let i = 0; i < encoded.length; i++) {
                let phone = PHONES[ALPHABET.indexOf(encoded[i])];
                if (/[012]/.test(encoded[i + 1] || '')) phone += encoded[++i];
                result.push(phone);
            }
            return result;
        }
    };
})();
'''
(root/'js/audio/ChattrLexicon.js').write_text(header + 'const ChattrLexicon = (() => {\n' +
    '    const PHONES = ' + json.dumps(phones) + ';\n    const ALPHABET = ' + json.dumps(alphabet) + ';\n' +
    '    const LICENSE = ' + json.dumps(files['chattr-cmudict.LICENSE']) + ';\n' +
    '    const DATA = ' + json.dumps('\n'.join(data)) + ';\n' + body)
print(f'{len(rows)} pronunciations; dictionary { (root/"js/audio/ChattrLexicon.js").stat().st_size:,} bytes')
